/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DiplomaNFT } from './DiplomaNFT.js';
export * as factories from './factories/index.js';
export { DiplomaNFT__factory } from './factories/DiplomaNFT__factory.js';